"""Pydantic schemas for Campaign."""
from pydantic import BaseModel, ConfigDict
from uuid import UUID
from datetime import datetime
from decimal import Decimal
from src.models.campaign import CampaignStatus


class CampaignBase(BaseModel):
    """Base Campaign schema."""

    brand_id: UUID
    market_id: UUID
    budget: Decimal
    status: CampaignStatus = CampaignStatus.DRAFT


class CampaignCreate(CampaignBase):
    """Schema for creating a Campaign."""

    campaign_name: str  # User-provided name for Taxonomy Engine


class CampaignUpdate(BaseModel):
    """Schema for updating a Campaign."""

    budget: Decimal | None = None
    status: CampaignStatus | None = None


class CampaignResponse(BaseModel):
    """Schema for Campaign response."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    name: str  # Generated by Taxonomy Engine
    brand_id: UUID
    market_id: UUID
    budget: Decimal
    status: CampaignStatus
    created_at: datetime
    updated_at: datetime
